### ISSUE TITLE
Won’t work

### ISSUE THREAD

**Issue by jkantner** [fhinkel/type-profile#2]
I ran `node demo.js` and got this:
```
/Users/jon/Downloads/type-profile-master/demo.js:7
inspector.Session.prototype.postAsync = function(...args) {
                 ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/jon/Downloads/type-profile-master/demo.js:7:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```
What am I missing?

**Comment by fhinkel** [comment]
That looks like you're using a Node version that doesn't support the inspector. I think the inspector is in Node 8. But for type profile you currently need to build node yourself with V8 tip of tree.
